export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS \
  --highlight-line \
  --info=inline-right \
  --ansi \
  --layout=reverse \
  --border=none \
  --color=bg+:#2d3f76 \
  --color=bg:#1e2030 \
  --color=border:#589ed7 \
  --color=fg:#ffffff \
  --color=gutter:#1e2030 \
  --color=header:#ffa500 \
  --color=hl+:#65bcff \
  --color=hl:#65bcff \
  --color=info:#989db1 \
  --color=marker:#ff00ff \
  --color=pointer:#ff00ff \
  --color=prompt:#65bcff \
  --color=query:#ffffff:regular \
  --color=scrollbar:#589ed7 \
  --color=separator:#ffa500 \
  --color=spinner:#ff00ff \
"
