export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS \
  --highlight-line \
  --info=inline-right \
  --ansi \
  --layout=reverse \
  --border=none \
  --color=bg+:#283457 \
  --color=bg:#16161e \
  --color=border:#27a1b9 \
  --color=fg:#ffffff \
  --color=gutter:#16161e \
  --color=header:#ffa500 \
  --color=hl+:#2ac3de \
  --color=hl:#2ac3de \
  --color=info:#989db1 \
  --color=marker:#ff00ff \
  --color=pointer:#ff00ff \
  --color=prompt:#2ac3de \
  --color=query:#ffffff:regular \
  --color=scrollbar:#27a1b9 \
  --color=separator:#ffa500 \
  --color=spinner:#ff00ff \
"
