export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS \
  --highlight-line \
  --info=inline-right \
  --ansi \
  --layout=reverse \
  --border=none \
  --color=bg+:#2e3c64 \
  --color=bg:#1f2335 \
  --color=border:#29a4bd \
  --color=fg:#ffffff \
  --color=gutter:#1f2335 \
  --color=header:#ffa500 \
  --color=hl+:#2ac3de \
  --color=hl:#2ac3de \
  --color=info:#989db1 \
  --color=marker:#ff00ff \
  --color=pointer:#ff00ff \
  --color=prompt:#2ac3de \
  --color=query:#ffffff:regular \
  --color=scrollbar:#29a4bd \
  --color=separator:#ffa500 \
  --color=spinner:#ff00ff \
"
