[colors]
foreground = "#474747"
background = "#e1e2e7"
cursor_bg = "#474747"
cursor_border = "#474747"
cursor_fg = "#e1e2e7"
selection_bg = "#b7c1e3"
selection_fg = "#474747"
split = "#2e7de9"
compose_cursor = "#9e6400"
scrollbar_thumb = "#c4c8da"

ansi = ["#b4b5b9", "#c50000", "#8c7500", "#4e4e00", "#2e7de9", "#d20065", "#006060", "#6172b0"]
brights = ["#a1a6c5", "#dc0000", "#9b8200", "#5a5a00", "#358aff", "#e90071", "#006d6d", "#474747"]

[colors.tab_bar]
inactive_tab_edge = "#d2d3d7"
background = "#e1e2e7"

[colors.tab_bar.active_tab]
fg_color = "#d2d3d7"
bg_color = "#2e7de9"

[colors.tab_bar.inactive_tab]
fg_color = "#8990b3"
bg_color = "#c4c8da"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#2e7de9"
bg_color = "#c4c8da"
# intensity = "Bold"

[colors.tab_bar.new_tab_hover]
fg_color = "#2e7de9"
bg_color = "#e1e2e7"
intensity = "Bold"

[colors.tab_bar.new_tab]
fg_color = "#2e7de9"
bg_color = "#e1e2e7"

[metadata]
aliases = []
author = "folke"
name = "tokyonight_day"