[colors]
foreground = "#ffffff"
background = "#222436"
cursor_bg = "#ffffff"
cursor_border = "#ffffff"
cursor_fg = "#222436"
selection_bg = "#2d3f76"
selection_fg = "#ffffff"
split = "#82aaff"
compose_cursor = "#ffa500"
scrollbar_thumb = "#2f334d"

ansi = ["#1b1d2b", "#ff3c3c", "#cdad00", "#ffff00", "#82aaff", "#ff007c", "#00ffff", "#828bb8"]
brights = ["#444a73", "#ff5f5f", "#ddba00", "#ffffff", "#9ab8ff", "#ff498a", "#c3ffff", "#ffffff"]

[colors.tab_bar]
inactive_tab_edge = "#1e2030"
background = "#222436"

[colors.tab_bar.active_tab]
fg_color = "#1e2030"
bg_color = "#82aaff"

[colors.tab_bar.inactive_tab]
fg_color = "#545c7e"
bg_color = "#2f334d"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#82aaff"
bg_color = "#2f334d"
# intensity = "Bold"

[colors.tab_bar.new_tab_hover]
fg_color = "#82aaff"
bg_color = "#222436"
intensity = "Bold"

[colors.tab_bar.new_tab]
fg_color = "#82aaff"
bg_color = "#222436"

[metadata]
aliases = []
author = "folke"
name = "tokyonight_moon"