[colors]
foreground = "#ffffff"
background = "#24283b"
cursor_bg = "#ffffff"
cursor_border = "#ffffff"
cursor_fg = "#24283b"
selection_bg = "#2e3c64"
selection_fg = "#ffffff"
split = "#7aa2f7"
compose_cursor = "#ffa500"
scrollbar_thumb = "#292e42"

ansi = ["#1d202f", "#ff3c3c", "#cdad00", "#ffff00", "#7aa2f7", "#ff007c", "#00ffff", "#a9b1d6"]
brights = ["#414868", "#ff5f5f", "#ddba00", "#ffffff", "#8db0ff", "#ff498a", "#c3ffff", "#ffffff"]

[colors.tab_bar]
inactive_tab_edge = "#1f2335"
background = "#24283b"

[colors.tab_bar.active_tab]
fg_color = "#1f2335"
bg_color = "#7aa2f7"

[colors.tab_bar.inactive_tab]
fg_color = "#989db1"
bg_color = "#292e42"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#7aa2f7"
bg_color = "#292e42"
# intensity = "Bold"

[colors.tab_bar.new_tab_hover]
fg_color = "#7aa2f7"
bg_color = "#24283b"
intensity = "Bold"

[colors.tab_bar.new_tab]
fg_color = "#7aa2f7"
bg_color = "#24283b"

[metadata]
aliases = []
author = "folke"
name = "tokyonight_storm"