[[themes]]
name = "Tokyo Night Storm"
[themes.palette]
background = "#1f2335"
foreground = "#a9b1d6"
black = "#414868"
<<<<<<< HEAD
red = "#ff4c4c"
=======
red = "#ff3c3c"
>>>>>>> custom_colors
green = "#cdad00"
yellow = "#ffff00"
blue = "#7aa2f7"
magenta = "#ff007c"
cyan = "#00ffff"
white = "${white}"
bright_black = "#24283b"
bright_red = "#7f0000"
bright_green = "#00c0c0"
bright_yellow = "#ffa500"
bright_blue = "#2ac3de"
bright_magenta = "#ff00ff"
bright_cyan = "#89ddff"
bright_white = "#ffffff"
