[[themes]]
name = "Tokyo Night Moon"
[themes.palette]
background = "#1e2030"
foreground = "#828bb8"
black = "#444a73"
<<<<<<< HEAD
red = "#ff4c4c"
=======
red = "#ff3c3c"
>>>>>>> custom_colors
green = "#cdad00"
yellow = "#ffff00"
blue = "#82aaff"
magenta = "#ff007c"
cyan = "#00ffff"
white = "${white}"
bright_black = "#222436"
bright_red = "#7f0000"
bright_green = "#00c0c0"
bright_yellow = "#ffa500"
bright_blue = "#65bcff"
bright_magenta = "#ff00ff"
bright_cyan = "#89ddff"
bright_white = "#ffffff"
