[[themes]]
name = "Tokyo Night Day"
[themes.palette]
background = "#d2d3d7"
foreground = "#6172b0"
black = "#a1a6c5"
<<<<<<< HEAD
red = "#c50000"
=======
red = "#cf0000"
>>>>>>> custom_colors
green = "#8c7500"
yellow = "#4e4e00"
blue = "#2e7de9"
magenta = "#d20065"
cyan = "#006060"
white = "${white}"
bright_black = "#e1e2e7"
bright_red = "#ff9d9d"
bright_green = "#008787"
bright_yellow = "#9e6400"
bright_blue = "#188092"
bright_magenta = "#f400f4"
bright_cyan = "#006a83"
bright_white = "#474747"
