[[themes]]
name = "Tokyo Night"
[themes.palette]
background = "#16161e"
foreground = "#a9b1d6"
black = "#414868"
red = "#ff4c4c"
green = "#cdad00"
yellow = "#ffff00"
blue = "#7aa2f7"
magenta = "#ff007c"
cyan = "#00ffff"
white = "${white}"
bright_black = "#1a1b26"
bright_red = "#7f0000"
bright_green = "#008080"
bright_yellow = "#ffa500"
bright_blue = "#2ac3de"
bright_magenta = "#ff00ff"
bright_cyan = "#89ddff"
bright_white = "#ffffff"
