attribute = { fg = "#00ffff" }
comment = { fg = "#565f89", modifiers = ["italic"] }
"comment.block.documentation" = { fg = "#ffff00" }
constant = { fg = "#ffa500" }
"constant.builtin" = { fg = "#2ac3de" }
"constant.builtin.boolean" = { fg = "#ffa500" }
"constant.character" = { fg = "#cdad00" }
"constant.character.escape" = { fg = "#ff007c" }
"constant.numeric" = { fg = "#ffa500" }
"constant.numeric.float" = { fg = "#ffa500" }
"constant.numeric.integer" = { fg = "#ffa500" }
constructor = { fg = "#2ac3de" }
"diagnostic.error" = { underline = { style = "curl" } }
"diagnostic.hint" = { underline = { style = "curl" } }
"diagnostic.info" = { underline = { style = "curl" } }
"diagnostic.warning" = { underline = { style = "curl" } }
"diff.delta" = { bg = "#272d43", fg = "#0000ff" }
"diff.delta.moved" = { fg = "#7aa2f7" }
"diff.minus" = { bg = "#322232", fg = "#ff0000" }
"diff.plus" = { bg = "#1f353c", fg = "#00ff00" }
error = { fg = "#7f0000" }
function = { fg = "#7aa2f7" }
"function.builtin" = { fg = "#2ac3de" }
"function.macro" = { fg = "#00ffff" }
"function.method" = { fg = "#7aa2f7" }
"function.special" = { fg = "#00ffff" }
hint = { fg = "#40e0d0" }
info = { fg = "#0db9d7" }
keyword = { fg = "#a64cff", modifiers = ["italic"] }
"keyword.control" = { fg = "#ff007c" }
"keyword.control.conditional" = { fg = "#ff007c" }
"keyword.control.exception" = { fg = "#ff007c" }
"keyword.control.repeat" = { fg = "#ff007c" }
"keyword.control.return" = { fg = "#a64cff", modifiers = ["italic"] }
"keyword.directive" = { fg = "#00ffff" }
"keyword.function" = { fg = "#ff007c" }
"keyword.operator" = { fg = "#ff007c" }
label = { fg = "#7aa2f7" }
"markup.bold" = { fg = "#ffffff", modifiers = ["bold"] }
"markup.heading" = { fg = "#7aa2f7", modifiers = ["bold"] }
"markup.heading.completion" = { bg = "#1f2335", fg = "#ffffff" }
"markup.heading.hover" = { bg = "#363d59" }
"markup.italic" = { fg = "#ffffff", modifiers = ["italic"] }
"markup.link" = { fg = "#40e0d0" }
"markup.link.label" = { fg = "#2ac3de" }
"markup.link.text" = { fg = "#40e0d0" }
"markup.link.url" = { underline = { style = "line" } }
"markup.list" = { fg = "#89ddff" }
"markup.normal.completion" = { fg = "#565f89" }
"markup.normal.hover" = { fg = "#a9b1d6" }
"markup.raw" = { fg = "#cdad00" }
"markup.raw.inline" = { bg = "#414868", fg = "#7aa2f7" }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
namespace = { fg = "#7aa2f7" }
operator = { fg = "#89ddff" }
special = { fg = "#2ac3de" }
string = { fg = "#cdad00" }
"string.regexp" = { fg = "#b4f9f8" }
"string.special" = { fg = "#2ac3de" }
tag = { fg = "#ff007c" }
type = { fg = "#2ac3de" }
"type.builtin" = { fg = "#29a4bd" }
"type.enum" = { fg = "#2ac3de" }
"type.enum.variant" = { fg = "#ffa500" }
"ui.background" = { bg = "bg" }
"ui.cursor" = { bg = "#ffffff", fg = "#24283b" }
"ui.cursor.match" = { fg = "#ffa500", modifiers = ["bold"] }
"ui.linenr" = { fg = "#3b4261" }
"ui.linenr.select" = { fg = "#ffa500", modifiers = ["bold"] }
"ui.menu" = { bg = "#1f2335", fg = "#ffffff" }
"ui.menu.scroll" = { bg = 2764351, fg = 3883617 }
"ui.menu.selected" = { bg = "#363d59" }
"ui.popup" = { bg = "#1f2335", fg = "#29a4bd" }
"ui.selection" = { bg = "bg_highlight" }
"ui.statusline" = { bg = "#1f2335", fg = "#a9b1d6" }
"ui.statusline.inactive" = { bg = "#1f2335", fg = "#3b4261" }
"ui.statusline.normal" = { bg = "blue", fg = "black" }
"ui.text" = { bg = "#24283b", fg = "#ffffff" }
"ui.text.focus" = { bg = "#2e3c64" }
"ui.text.inactive" = { fg = "#565f89", modifiers = ["italic"] }
"ui.text.info" = { bg = "#1f2335", fg = "#ffffff" }
"ui.virtual.inlay-hint" = { bg = "#273a4a", fg = "#40e0d0" }
"ui.window" = { fg = "#1d202f", modifiers = ["bold"] }
variable = { fg = "#ffffff" }
"variable.builtin" = { fg = "#ff4c4c" }
"variable.other.member" = { fg = "#008080" }
"variable.parameter" = { fg = "#ffff00" }
warning = { fg = "#ffff00" }

[palette]
bg = "#24283b"
bg_dark = "#1f2335"
bg_dark1 = "#1b1e2d"
bg_float = "#1f2335"
bg_highlight = "#292e42"
bg_popup = "#1f2335"
bg_search = "#3d59a1"
bg_sidebar = "#1f2335"
bg_statusline = "#1f2335"
bg_visual = "#2e3c64"
black = "#1d202f"
blue = "#7aa2f7"
blue0 = "#3d59a1"
blue1 = "#2ac3de"
blue2 = "#0db9d7"
blue5 = "#89ddff"
blue6 = "#b4f9f8"
blue7 = "#394b70"
border = "#1d202f"
border_highlight = "#29a4bd"
comment = "#565f89"
cyan = "#00ffff"
dark3 = "#545c7e"
dark5 = "#737aa2"
"diff.add" = "#1f353c"
"diff.change" = "#272d43"
"diff.delete" = "#322232"
"diff.text" = "#394b70"
error = "#7f0000"
fg = "#ffffff"
fg_dark = "#a9b1d6"
fg_float = "#ffffff"
fg_gutter = "#3b4261"
fg_sidebar = "#a9b1d6"
"git.add" = "#00ff00"
"git.change" = "#0000ff"
"git.delete" = "#ff0000"
"git.ignore" = "#545c7e"
green = "#cdad00"
green1 = "#008080"
green2 = "#008040"
hint = "#40e0d0"
info = "#0db9d7"
magenta = "#ff007c"
magenta2 = "#ff00ff"
orange = "#ffa500"
purple = "#a64cff"
rainbow = "#7aa2f7"
"rainbow.2" = "#ffff00"
"rainbow.3" = "#cdad00"
"rainbow.4" = "#40e0d0"
"rainbow.5" = "#ff007c"
"rainbow.6" = "#a64cff"
"rainbow.7" = "#ffa500"
"rainbow.8" = "#ff4c4c"
red = "#ff4c4c"
red1 = "#7f0000"
teal = "#40e0d0"
"terminal.black" = "#1d202f"
"terminal.black_bright" = "#414868"
"terminal.blue" = "#7aa2f7"
"terminal.blue_bright" = "#8db0ff"
"terminal.cyan" = "#00ffff"
"terminal.cyan_bright" = "#c3ffff"
"terminal.green" = "#cdad00"
"terminal.green_bright" = "#ddba00"
"terminal.magenta" = "#ff007c"
"terminal.magenta_bright" = "#ff498a"
"terminal.red" = "#ff4c4c"
"terminal.red_bright" = "#ff6a6a"
"terminal.white" = "#a9b1d6"
"terminal.white_bright" = "#ffffff"
"terminal.yellow" = "#ffff00"
"terminal.yellow_bright" = "#ffffff"
terminal_black = "#414868"
todo = "#7aa2f7"
warning = "#ffff00"
yellow = "#ffff00"