[manager]
# NOTE: can combined with tmTheme (sublime colorshceme file) for preview code highlight
# syntect_theme = "path/to/tmTheme"

cwd = { fg = "#6172b0", italic = true }

# Hovered
hovered         = { bg = "#c4c8da" }
preview_hovered = { bg = "#c4c8da" }

# Find
find_keyword  = { fg = "#d2d3d7", bg = "#9e6400", bold = true }
find_position = { fg = "#07879d", bg = "#cbd9e0", bold = true }

# Marker
marker_copied   = { fg = "#008787", bg = "#008787" }
marker_cut      = { fg = "#cf0000", bg = "#cf0000" }
marker_marked   = { fg = "#d20065", bg = "#d20065" }
marker_selected = { fg = "#2e7de9", bg = "#2e7de9" }

# Tab
tab_active   = { fg = "#474747", bg = "#c4c8da" }
tab_inactive = { fg = "#a8aecb", bg = "#e1e2e7" }
tab_width    = 1

# Count
count_copied   = { fg = "#474747", bg = "#009046" }
count_cut      = { fg = "#474747", bg = "#ff9d9d" }
count_selected = { fg = "#474747", bg = "#7890dd" }

# Border
border_symbol = "│"
border_style  = { fg = "#4094a3" }

[mode]
normal_main = { fg = "#b4b5b9", bg = "#2e7de9", bold = true }
normal_alt  = { fg = "#2e7de9", bg = "#a8aecb" }

select_main = { fg = "#b4b5b9", bg = "#d20065", bold = true }
select_alt  = { fg = "#d20065", bg = "#a8aecb" }

unset_main  = { fg = "#b4b5b9", bg = "#a02cff", bold = true }
unset_alt   = { fg = "#a02cff", bg = "#a8aecb" }

[status]
separator_open    = ""
separator_close   = ""
# separator_style = { fg = "#a8aecb", bg = "#a8aecb" }

# Progress
progress_label  = { fg = "#6172b0", bold = true }
progress_normal = { fg = "#e1e2e7" }
progress_error  = { fg = "#cf0000" }

# Permissions
perm_type  = { fg = "#2e7de9" }
perm_read  = { fg = "#4e4e00" }
perm_write = { fg = "#cf0000" }
perm_exec  = { fg = "#8c7500" }
perm_sep   = { fg = "#a1a6c5" }

[pick]
border   = { fg = "#4094a3" }
active   = { fg = "#474747",  bg = "#b7c1e3" }
inactive = { fg = "#474747" }

# Input
[input]
border   = { fg = "#07879d" }
title    = { fg = "#07879d" }
value    = { fg = "#a02cff" }
selected = { bg = "#b7c1e3" }

# Completion
[completion]
border   = { fg = "#07879d" }
active   = { fg = "#474747", bg = "#b7c1e3" }
inactive = { fg = "#474747" }

icon_file    = ""
icon_folder  = ""
icon_command = ""

# Tasks
[tasks]
border  = { fg = "#4094a3" }
title   = { fg = "#4094a3" }
hovered = { fg = "#474747", bg="#b7c1e3" }

# Which
[which]
cols            = 3
mask            = { bg = "#d2d3d7" }
cand            = { fg = "#006060" }
rest            = { fg = "#2e7de9" }
desc            = { fg = "#d20065" }
separator       = " ➜ "
separator_style = { fg = "#7880a0" }

# Confirm
[confirm]
border  = { fg = "#07879d" }
title   = { fg = "#4094a3" }
content = {}
list    = {}
btn_yes = { bg = "#b7c1e3" }
btn_no  = {}
btn_labels = [ "  [Y]es  ", "  (N)o  " ]

# Spot
[spot]
border  = { fg = "#4094a3" }
title   = { fg = "#4094a3" }

# Notify
[notify]
title_info  = { fg = "#07879d" }
title_warn  = { fg = "#4e4e00" }
title_error = { fg = "#ff9d9d" }

icon_error = ""
icon_warn = ""
icon_info = ""

# Help
[help]
on      = { fg = "#8c7500" }
run     = { fg = "#d20065" }
hovered = { bg = "#c4c8da" }
footer  = { fg = "#474747", bg = "#e1e2e7" }

[filetype]

rules = [
	# Images
	{ mime = "image/*", fg = "#4e4e00" },

	# Media
	{ mime = "{audio,video}/*", fg = "#d20065" },

	# Archives
	{ mime = "application/*zip", fg = "#cf0000" },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#cf0000" },

	# Documents
	{ mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#006060" },

	# Empty files
	# { mime = "inode/x-empty", fg = "#cf0000" },

	# Special files
	{ name = "*", is = "orphan", bg = "#cf0000" },
	{ name = "*", is = "exec"  , fg = "#8c7500" },

	# Fallback
	{ name = "*/", fg = "#2e7de9" }
]
    