[manager]
# NOTE: can combined with tmTheme (sublime colorshceme file) for preview code highlight
# syntect_theme = "path/to/tmTheme"

cwd = { fg = "#a9b1d6", italic = true }

# Hovered
hovered         = { bg = "#292e42" }
preview_hovered = { bg = "#292e42" }

# Find
find_keyword  = { fg = "#1f2335", bg = "#ffa500", bold = true }
find_position = { fg = "#0db9d7", bg = "#22374b", bold = true }

# Marker
marker_copied   = { fg = "#00c0c0", bg = "#00c0c0" }
<<<<<<< HEAD
marker_cut      = { fg = "#ff4c4c", bg = "#ff4c4c" }
=======
marker_cut      = { fg = "#ff3c3c", bg = "#ff3c3c" }
>>>>>>> custom_colors
marker_marked   = { fg = "#ff007c", bg = "#ff007c" }
marker_selected = { fg = "#7aa2f7", bg = "#7aa2f7" }

# Tab
tab_active   = { fg = "#ffffff", bg = "#292e42" }
tab_inactive = { fg = "#3b4261", bg = "#24283b" }
tab_width    = 1

# Count
count_copied   = { fg = "#ffffff", bg = "#00c060" }
count_cut      = { fg = "#ffffff", bg = "#7f0000" }
count_selected = { fg = "#ffffff", bg = "#3d59a1" }

# Border
border_symbol = "│"
border_style  = { fg = "#29a4bd" }

[mode]
normal_main = { fg = "#1d202f", bg = "#7aa2f7", bold = true }
normal_alt  = { fg = "#7aa2f7", bg = "#3b4261" }

select_main = { fg = "#1d202f", bg = "#ff007c", bold = true }
select_alt  = { fg = "#ff007c", bg = "#3b4261" }

unset_main  = { fg = "#1d202f", bg = "#a64cff", bold = true }
unset_alt   = { fg = "#a64cff", bg = "#3b4261" }

[status]
separator_open    = ""
separator_close   = ""
# separator_style = { fg = "#3b4261", bg = "#3b4261" }

# Progress
progress_label  = { fg = "#a9b1d6", bold = true }
progress_normal = { fg = "#24283b" }
<<<<<<< HEAD
progress_error  = { fg = "#ff4c4c" }
=======
progress_error  = { fg = "#ff3c3c" }
>>>>>>> custom_colors

# Permissions
perm_type  = { fg = "#7aa2f7" }
perm_read  = { fg = "#ffff00" }
<<<<<<< HEAD
perm_write = { fg = "#ff4c4c" }
=======
perm_write = { fg = "#ff3c3c" }
>>>>>>> custom_colors
perm_exec  = { fg = "#cdad00" }
perm_sep   = { fg = "#414868" }

[pick]
border   = { fg = "#29a4bd" }
active   = { fg = "#ffffff",  bg = "#2e3c64" }
inactive = { fg = "#ffffff" }

# Input
[input]
border   = { fg = "#0db9d7" }
title    = { fg = "#0db9d7" }
value    = { fg = "#a64cff" }
selected = { bg = "#2e3c64" }

# Completion
[completion]
border   = { fg = "#0db9d7" }
active   = { fg = "#ffffff", bg = "#2e3c64" }
inactive = { fg = "#ffffff" }

icon_file    = ""
icon_folder  = ""
icon_command = ""

# Tasks
[tasks]
border  = { fg = "#29a4bd" }
title   = { fg = "#29a4bd" }
hovered = { fg = "#ffffff", bg="#2e3c64" }

# Which
[which]
cols            = 3
mask            = { bg = "#1f2335" }
cand            = { fg = "#00ffff" }
rest            = { fg = "#7aa2f7" }
desc            = { fg = "#ff007c" }
separator       = " ➜ "
separator_style = { fg = "#565f89" }

# Confirm
[confirm]
border  = { fg = "#0db9d7" }
title   = { fg = "#29a4bd" }
content = {}
list    = {}
btn_yes = { bg = "#2e3c64" }
btn_no  = {}
btn_labels = [ "  [Y]es  ", "  (N)o  " ]

# Spot
[spot]
border  = { fg = "#29a4bd" }
title   = { fg = "#29a4bd" }

# Notify
[notify]
title_info  = { fg = "#0db9d7" }
title_warn  = { fg = "#ffff00" }
title_error = { fg = "#7f0000" }

icon_error = ""
icon_warn = ""
icon_info = ""

# Help
[help]
on      = { fg = "#cdad00" }
run     = { fg = "#ff007c" }
hovered = { bg = "#292e42" }
footer  = { fg = "#ffffff", bg = "#24283b" }

[filetype]

rules = [
	# Images
	{ mime = "image/*", fg = "#ffff00" },

	# Media
	{ mime = "{audio,video}/*", fg = "#ff007c" },

	# Archives
<<<<<<< HEAD
	{ mime = "application/*zip", fg = "#ff4c4c" },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#ff4c4c" },
=======
	{ mime = "application/*zip", fg = "#ff3c3c" },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#ff3c3c" },
>>>>>>> custom_colors

	# Documents
	{ mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#00ffff" },

	# Empty files
<<<<<<< HEAD
	# { mime = "inode/x-empty", fg = "#ff4c4c" },

	# Special files
	{ name = "*", is = "orphan", bg = "#ff4c4c" },
=======
	# { mime = "inode/x-empty", fg = "#ff3c3c" },

	# Special files
	{ name = "*", is = "orphan", bg = "#ff3c3c" },
>>>>>>> custom_colors
	{ name = "*", is = "exec"  , fg = "#cdad00" },

	# Fallback
	{ name = "*/", fg = "#7aa2f7" }
]
    