[manager]
# NOTE: can combined with tmTheme (sublime colorshceme file) for preview code highlight
# syntect_theme = "path/to/tmTheme"

cwd = { fg = "#828bb8", italic = true }

# Hovered
hovered         = { bg = "#2f334d" }
preview_hovered = { bg = "#2f334d" }

# Find
find_keyword  = { fg = "#1e2030", bg = "#ffa500", bold = true }
find_position = { fg = "#0db9d7", bg = "#203346", bold = true }

# Marker
marker_copied   = { fg = "#00c0c0", bg = "#00c0c0" }
<<<<<<< HEAD
marker_cut      = { fg = "#ff4c4c", bg = "#ff4c4c" }
=======
marker_cut      = { fg = "#ff3c3c", bg = "#ff3c3c" }
>>>>>>> custom_colors
marker_marked   = { fg = "#ff007c", bg = "#ff007c" }
marker_selected = { fg = "#82aaff", bg = "#82aaff" }

# Tab
tab_active   = { fg = "#ffffff", bg = "#2f334d" }
tab_inactive = { fg = "#3b4261", bg = "#222436" }
tab_width    = 1

# Count
count_copied   = { fg = "#ffffff", bg = "#00c060" }
count_cut      = { fg = "#ffffff", bg = "#7f0000" }
count_selected = { fg = "#ffffff", bg = "#3e68d7" }

# Border
border_symbol = "│"
border_style  = { fg = "#589ed7" }

[mode]
normal_main = { fg = "#1b1d2b", bg = "#82aaff", bold = true }
normal_alt  = { fg = "#82aaff", bg = "#3b4261" }

select_main = { fg = "#1b1d2b", bg = "#ff007c", bold = true }
select_alt  = { fg = "#ff007c", bg = "#3b4261" }

unset_main  = { fg = "#1b1d2b", bg = "#a64cff", bold = true }
unset_alt   = { fg = "#a64cff", bg = "#3b4261" }

[status]
separator_open    = ""
separator_close   = ""
# separator_style = { fg = "#3b4261", bg = "#3b4261" }

# Progress
progress_label  = { fg = "#828bb8", bold = true }
progress_normal = { fg = "#222436" }
<<<<<<< HEAD
progress_error  = { fg = "#ff4c4c" }
=======
progress_error  = { fg = "#ff3c3c" }
>>>>>>> custom_colors

# Permissions
perm_type  = { fg = "#82aaff" }
perm_read  = { fg = "#ffff00" }
<<<<<<< HEAD
perm_write = { fg = "#ff4c4c" }
=======
perm_write = { fg = "#ff3c3c" }
>>>>>>> custom_colors
perm_exec  = { fg = "#cdad00" }
perm_sep   = { fg = "#444a73" }

[pick]
border   = { fg = "#589ed7" }
active   = { fg = "#ffffff",  bg = "#2d3f76" }
inactive = { fg = "#ffffff" }

# Input
[input]
border   = { fg = "#0db9d7" }
title    = { fg = "#0db9d7" }
value    = { fg = "#a64cff" }
selected = { bg = "#2d3f76" }

# Completion
[completion]
border   = { fg = "#0db9d7" }
active   = { fg = "#ffffff", bg = "#2d3f76" }
inactive = { fg = "#ffffff" }

icon_file    = ""
icon_folder  = ""
icon_command = ""

# Tasks
[tasks]
border  = { fg = "#589ed7" }
title   = { fg = "#589ed7" }
hovered = { fg = "#ffffff", bg="#2d3f76" }

# Which
[which]
cols            = 3
mask            = { bg = "#1e2030" }
cand            = { fg = "#00ffff" }
rest            = { fg = "#82aaff" }
desc            = { fg = "#ff007c" }
separator       = " ➜ "
separator_style = { fg = "#636da6" }

# Confirm
[confirm]
border  = { fg = "#0db9d7" }
title   = { fg = "#589ed7" }
content = {}
list    = {}
btn_yes = { bg = "#2d3f76" }
btn_no  = {}
btn_labels = [ "  [Y]es  ", "  (N)o  " ]

# Spot
[spot]
border  = { fg = "#589ed7" }
title   = { fg = "#589ed7" }

# Notify
[notify]
title_info  = { fg = "#0db9d7" }
title_warn  = { fg = "#ffff00" }
title_error = { fg = "#7f0000" }

icon_error = ""
icon_warn = ""
icon_info = ""

# Help
[help]
on      = { fg = "#cdad00" }
run     = { fg = "#ff007c" }
hovered = { bg = "#2f334d" }
footer  = { fg = "#ffffff", bg = "#222436" }

[filetype]

rules = [
	# Images
	{ mime = "image/*", fg = "#ffff00" },

	# Media
	{ mime = "{audio,video}/*", fg = "#ff007c" },

	# Archives
<<<<<<< HEAD
	{ mime = "application/*zip", fg = "#ff4c4c" },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#ff4c4c" },
=======
	{ mime = "application/*zip", fg = "#ff3c3c" },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", fg = "#ff3c3c" },
>>>>>>> custom_colors

	# Documents
	{ mime = "application/{pdf,doc,rtf,vnd.*}", fg = "#00ffff" },

	# Empty files
<<<<<<< HEAD
	# { mime = "inode/x-empty", fg = "#ff4c4c" },

	# Special files
	{ name = "*", is = "orphan", bg = "#ff4c4c" },
=======
	# { mime = "inode/x-empty", fg = "#ff3c3c" },

	# Special files
	{ name = "*", is = "orphan", bg = "#ff3c3c" },
>>>>>>> custom_colors
	{ name = "*", is = "exec"  , fg = "#cdad00" },

	# Fallback
	{ name = "*/", fg = "#82aaff" }
]
    